name: Post JSON File to Two URLs

on:
  push:
    branches:
      - main  # Runs only when pushing to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data to First URL
        run: |
          curl https://:QDUp8VqgR9aFT31O7Lvpqg@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:66My2G3TQWWzuKDArwBs4A/streams/AQAAAOUtgpaDTU-3vcyopR9wgrcAAAAA

      - name: Send JSON Data to Second URL
        run: |
          curl https://:nlU17jSJQuKlmeQtMq8uNg@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:66My2G3TQWWzuKDArwBs4A/streams/AQAAAF_IyXetU0kajODEWdVrQIsAAAAA
